spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: update  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
  batch:
    job:
      names: ${job.name:NONE}
  redis:
    host: localhost
    port: 6379

mail:
  address:
    admin: admin@gmail.com

jwt:
  key: 121312313212313212312312312341534564564154153131321321351534654646463135131534354435131023135463      # 민감한 정보는 시스템 환경 변수에서 로드한다.
  access-token-expiration-minutes: 300
  refresh-token-expiration-minutes: 420


